name: flavor_tools
description: Easily create and manage application flavors
version: 1.0.5
repository: https://github.com/EclipseAndrey/flavor_tools

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  xcode_parser: ^1.0.6
  args: ^2.0.0
  xml: ^6.5.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
